on: [push]

name: check-no-error

jobs:
  check-no-error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0.0'
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install renv
        run: Rscript -e "install.packages('renv')"
      - name: Restore packages
        run: Rscript -e "renv::restore()"
      - name: Test
        run: Rscript ~/testthat/test-test_r_gh_actions.R
